package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	//"os"
)

type AutoGenerated struct {
	Abilities []struct {
		Ability struct {
			Name string `json:"name"`
		} `json:"ability"`
	} `json:"abilities"`
	Name  string `json:"name"`
	Types []struct {
		Type struct {
			Name string `json:"name"`
		} `json:"type"`
	} `json:"types"`
	Weight int `json:"weight"`
}

func main() {
	poke, _ := http.Get("http://pokeapi.co/api/v2/pokemon/")
	data := map[string]interface{}{}
	poker, _ := ioutil.ReadAll(poke.Body)
	err4 := json.Unmarshal(poker, &data)
	checkerr(err4)

}

func checkerr(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
